spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://Rexxwell:skhi4yU0kYp2hynT@cluster0.gtzs7kd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=nutricast
spring.data.mongodb.authentication-database = admin